import cyvr from '../src/adapters/reality/data/cyvr.json';
import {it,expect} from 'vitest';import {readAirportCapture,feetToMetres} from '../src/adapters/reality/airports';
const source={dataset:'Synthetic airport fixture',url:'https://example.test',retrievedAt:'2026-10-03T00:00:00Z'};const airport={id:'CYVR',iata:'YVR',name:'Vancouver fixture',position:{lat:49.19,lon:-123.18},sources:[source],airlines:[{code:'AC',name:'Air Canada',colours:['#eeeeee','#cc0000'],sourceUrl:'https://www.yvr.ca/en/passengers/flights/airlines-and-destinations',representation:'stylized'}],runways:[{id:'08R-26L',airportId:'CYVR',ends:[{lat:49.19,lon:-123.208},{lat:49.184,lon:-123.161}],endNames:['08R','26L'],lengthM:3505.2,closed:false,elevationM:3,verticalDatum:'CGVD2013'}]};
it('keeps physical runway ends and airline source',()=>{const c=readAirportCapture(airport);expect(c.runways[0].endNames).toEqual(['08R','26L']);expect(c.airlines[0].sourceUrl).toBe(airport.airlines[0].sourceUrl);});
it('converts feet without treating airport elevation as runway elevation',()=>{expect(feetToMetres(11500)).toBeCloseTo(3505.2);expect(feetToMetres(9)).toBeCloseTo(2.7432);});
it('rejects other-airport runways, invalid endpoints and missing height datum',()=>{expect(()=>readAirportCapture({...airport,runways:[{...airport.runways[0],airportId:'CYXX'}]})).toThrow();expect(()=>readAirportCapture({...airport,runways:[{...airport.runways[0],ends:[{lat:NaN,lon:0},{lat:0,lon:0}]}]})).toThrow();expect(()=>readAirportCapture({...airport,runways:[{...airport.runways[0],verticalDatum:undefined}]})).toThrow();});
it('preserves closed runway status without silently activating it',()=>{expect(readAirportCapture({...airport,runways:[{...airport.runways[0],closed:true}]}).runways[0].closed).toBe(true);});

it('captures only CYVR physical runways with scene-compatible derived heights',()=>{const c=readAirportCapture(cyvr);expect(c.id).toBe('CYVR');expect(c.runways.filter(r=>!r.closed).map(r=>r.endNames.join('/')).sort()).toEqual(['08L/26R','08R/26L','13/31']);expect(c.runways.every(r=>r.airportId==='CYVR'&&r.verticalDatum==='CGVD2013'&&r.elevationMethod==='derived')).toBe(true);expect(c.runways.find(r=>r.endNames[0]==='08R')!.reported!.lengthFt).toBe(11500);});
