import {it,expect} from 'vitest';
import {readMaritimeCapture} from '../src/adapters/reality/maritime';
const source={dataset:'synthetic-fixture',url:'https://example.test',territoryId:'CA-BC',retrievedAt:'2026-10-03T00:00:00Z',observedYear:2026,method:'reported'};
const terminal={id:'canada-place',name:'Canada Place fixture',operator:'Port fixture',position:{lat:49.29,lon:-123.11},berths:['west'],source,allowedKinds:['cruise']};
it('retains operator and source identity instead of conflating Aquabus with another ferry',()=>{const capture=readMaritimeCapture({terminals:[{...terminal,id:'aquabus',operator:'Aquabus',allowedKinds:['aquabus']}],routes:[],cruiseCalls:[]});expect(capture.terminals[0].operator).toBe('Aquabus');});
it('refuses duplicate berth identities and invalid coordinates',()=>{expect(()=>readMaritimeCapture({terminals:[terminal,{...terminal,id:'other'}],routes:[],cruiseCalls:[]})).toThrow();expect(()=>readMaritimeCapture({terminals:[{...terminal,position:{lat:100,lon:0}}],routes:[],cruiseCalls:[]})).toThrow();});
it('does not turn a 2025 cruise calendar into a 2026 call',()=>{const call={id:'fixture-call',vesselName:'Fixture ship',company:'Fixture company',terminalId:terminal.id,berthId:'west',arrival:'2026-10-03T07:00:00Z',departure:'2026-10-04T07:00:00Z',source:{...source,observedYear:2025}};expect(()=>readMaritimeCapture({terminals:[terminal],routes:[],cruiseCalls:[call]})).toThrow();});
it('keeps the verified 2026 source capture and dated display windows',async()=>{const {default:data}=await import('../src/adapters/reality/data/vancouver-maritime.json');const capture=readMaritimeCapture(data);expect(capture.routes.filter(r=>r.allowed.includes('seabus'))).toHaveLength(2);expect(capture.routes.filter(r=>r.allowed.includes('aquabus'))).toHaveLength(7);expect(capture.cruiseCalls.find(c=>c.vesselName==='Koningsdam')!.berthId).toBe('canada-place:west');expect(capture.cruiseCalls.every(c=>c.windowMethod==='derived')).toBe(true);});
it('refuses an illustrative berth position for an undeclared berth',()=>{expect(()=>readMaritimeCapture({terminals:[{...terminal,berthPositions:{unknown:{lat:49.29,lon:-123.11}}}],routes:[],cruiseCalls:[]})).toThrow();});
