import {it,expect} from 'vitest';
import {buildNetworkJob,createNetworkJobQueue,type NetworkRequest,type NetworkResult} from '../src/presentation/mobility-network-job';
const request=(ticket:number):NetworkRequest=>({ticket,revision:String(ticket),tiles:[],maxEdges:140000});
it('coalesces pending work and rejects obsolete and disposed results',async()=>{const started:number[]=[],resolve:((r:NetworkResult)=>void)[]=[],published:number[]=[];const q=createNetworkJobQueue(r=>new Promise(done=>{started.push(r.ticket);resolve.push(done);}),r=>published.push(r.ticket));q.submit(request(1));q.submit(request(2));q.submit(request(3));expect(q.stats()).toEqual({active:1,pending:1});resolve.shift()!(buildNetworkJob(request(1)));await new Promise(r=>setTimeout(r,0));expect(started).toEqual([1,3]);expect(published).toEqual([]);resolve.shift()!(buildNetworkJob(request(3)));await new Promise(r=>setTimeout(r,0));expect(published).toEqual([3]);q.submit(request(4));q.dispose();resolve.shift()!(buildNetworkJob(request(4)));await new Promise(r=>setTimeout(r,0));expect(published).toEqual([3]);});
it('limits topology by complete tile regions and never returns dangling edges',()=>{const tiles=Array.from({length:4},(_,i)=>({z:14,x:i,y:0,features:[{layer:'streets',kind:'residential',bridge:false,type:2,geometry:[[{x:i*100,y:0},{x:i*100+10,y:0}]]}]}));const result=buildNetworkJob({...request(1),tiles,maxEdges:3});expect(result.limited).toBe(true);expect(result.network.edges.size).toBeLessThanOrEqual(3);for(const e of result.network.edges.values()){expect(result.network.nodes.has(e.from)).toBe(true);expect(result.network.nodes.has(e.to)).toBe(true);}expect(result.acceptedTileKeys).toHaveLength(1);});
it('rejects oversized tile input before intersection geometry is expanded',()=>{
 const huge={z:14,x:0,y:0,features:[{layer:'streets',kind:'residential',bridge:false,type:2,geometry:[Array.from({length:5000},(_,x)=>({x,y:0}))]}]};
 const result=buildNetworkJob({...request(1),tiles:[huge],maxEdges:100});
 expect(result.acceptedTileKeys).toEqual([]);expect(result.limited).toBe(true);expect(result.network.edges.size).toBe(0);
});
it('keeps useful complete nearby street paths when an urban tile exceeds the network quota',()=>{const tile={z:14,x:0,y:0,features:[{layer:'streets',kind:'residential',bridge:false,type:2,geometry:Array.from({length:100},(_,i)=>[{x:i*10,y:0},{x:i*10+5,y:0}])}]};const result=buildNetworkJob({...request(1),tiles:[tile],maxEdges:10,center:{x:505,y:0}});expect(result.limited).toBe(true);expect(result.network.edges.size).toBeGreaterThan(0);expect(result.network.edges.size).toBeLessThanOrEqual(10);expect(result.acceptedTileKeys).toEqual(['14:0:0']);expect([...result.network.nodes.values()].some(n=>n.point.x===500)).toBe(true);for(const edge of result.network.edges.values()){expect(result.network.nodes.has(edge.from)).toBe(true);expect(result.network.nodes.has(edge.to)).toBe(true);}});
