import {it,expect} from 'vitest';
import {createSceneCompositor,dirtyRegions} from '../src/surfaces/canvas/scene-compositor';
it('merges old and new bounds and falls back on excessive area or fragmentation',()=>{expect(dirtyRegions([{x:0,y:0,width:10,height:10},{x:8,y:0,width:10,height:10}],100,100)).toEqual([{x:0,y:0,width:18,height:10}]);expect(dirtyRegions([{x:0,y:0,width:100,height:50}],100,100)).toBeNull();expect(dirtyRegions(Array.from({length:33},(_,i)=>({x:i*20,y:0,width:2,height:2})),1000,1000)).toBeNull();});
it('restores both actor locations and draws intersecting static volumes in depth order',()=>{const calls:string[]=[],clips:unknown[][]=[];const ctx={save(){},restore(){},beginPath(){},rect(...r:unknown[]){clips.push(r);},clip(){}} as unknown as CanvasRenderingContext2D;
 const compositor=createSceneCompositor(),staticCommand={depth:10,bounds:{x:0,y:0,width:20,height:20},draw:()=>calls.push('building')},first={depth:5,bounds:{x:2,y:2,width:4,height:4},draw:()=>calls.push('car')},key={};
 compositor.compose(ctx,key,100,100,()=>calls.push('ground'),[staticCommand],[first]);expect(calls).toEqual(['ground','car','building']);calls.length=0;
 compositor.compose(ctx,key,100,100,()=>calls.push('ground'),[staticCommand],[{...first,bounds:{x:40,y:40,width:4,height:4}}]);expect(clips).toContainEqual([2,2,4,4]);expect(clips).toContainEqual([40,40,4,4]);expect(calls).toEqual(['ground','car','building']);expect(compositor.stats().staticBuilds).toBe(1);
});
it('new revision redraws full scene, clears prior dirty bounds and supports unchanged pause',()=>{const c=createSceneCompositor(),ctx={save(){},restore(){},beginPath(){},rect(){},clip(){}} as unknown as CanvasRenderingContext2D;let paints=0;const key={};c.compose(ctx,key,100,100,()=>paints++,[],[]);c.compose(ctx,key,100,100,()=>paints++,[],[]);expect(paints).toBe(1);c.compose(ctx,{},100,100,()=>paints++,[],[]);expect(paints).toBe(2);c.clear();expect(c.stats().dirtyRegions).toBe(0);});

it('airborne overlay locations are restored without double drawing transparent volumes',()=>{const c=createSceneCompositor(),calls:string[]=[],ctx={save(){},restore(){},beginPath(){},rect(){},clip(){}} as unknown as CanvasRenderingContext2D,key={};const glass={depth:1,bounds:{x:0,y:0,width:20,height:20},draw:()=>calls.push('glass')},air={depth:Infinity,bounds:{x:2,y:2,width:4,height:4},draw:()=>calls.push('air')};c.compose(ctx,key,100,100,()=>calls.push('ground'),[glass],[air]);calls.length=0;c.compose(ctx,key,100,100,()=>calls.push('ground'),[glass],[{...air,bounds:{x:30,y:30,width:4,height:4}}]);expect(calls).toEqual(['ground','glass','air']);});
