import {expect,it,vi} from 'vitest';
import {createSceneWorkerClient} from '../src/browser/scene-worker-client';
import type {SceneWorkerRequest,SceneWorkerResult} from '../src/browser/scene-worker-protocol';
import {createGame} from '../src/core/commands';
import {blank} from './fixtures/world';
import type {WorldView} from '../src/surfaces/canvas/canvas-renderer';
const view:WorldView={camera:{x:100,y:100,zoom:.35,rotation:0},viewport:{width:400,height:300},state:createGame('fixture',1,blank('0:0')),chunks:new Map(),tool:'explore',hover:null,preview:[],previewAffordable:true,seed:1,motion:0,geography:{revision:1,loading:false,error:false,tiles:[]}};
const result=(r:SceneWorkerRequest):SceneWorkerResult=>({ticket:r.ticket,key:r.key,staticReady:true,bitmap:{close:vi.fn()} as unknown as ImageBitmap,cache:{bytes:0,entries:0},workMs:1});
it('coalesces frames, sends static inputs only when changed and closes stale transferred images',()=>{const sent:SceneWorkerRequest[]=[],published:SceneWorkerResult[]=[],worker={onmessage:null as ((e:{data:SceneWorkerResult})=>void)|null,onerror:null as (()=>void)|null,postMessage(r:SceneWorkerRequest){sent.push(r);},terminate:vi.fn()},c=createSceneWorkerClient(()=>worker as unknown as Worker,()=>{},r=>published.push(r));c.submit(view);expect(sent[0].scene?.state).toBeDefined();c.submit({...view,motion:1});c.submit({...view,motion:2});expect(sent).toHaveLength(1);worker.onmessage!({data:result(sent[0])});expect(sent).toHaveLength(2);expect(sent[1].scene).toBeUndefined();expect(sent[1].motion).toBe(2);expect(published).toHaveLength(1);c.submit({...view,camera:{...view.camera,x:200}});const old=result(sent[1]);worker.onmessage!({data:old});expect(old.bitmap.close).toHaveBeenCalledOnce();expect(sent).toHaveLength(3);c.dispose();const late=result(sent[2]);worker.onmessage!({data:late});expect(late.bitmap.close).toHaveBeenCalledOnce();expect(worker.terminate).toHaveBeenCalledOnce();});
it('does not advance dynamics until static completion and degrades cleanly when workers fail',()=>{let failed=0;const worker={onmessage:null as ((e:{data:SceneWorkerResult})=>void)|null,onerror:null as (()=>void)|null,postMessage:vi.fn(),terminate:vi.fn()},c=createSceneWorkerClient(()=>worker as unknown as Worker,()=>failed++,()=>{});expect(c.ready(view)).toBe(false);c.submit(view);const request=worker.postMessage.mock.calls[0][0];worker.onmessage!({data:result(request)});expect(c.ready(view)).toBe(true);expect(c.ready({...view,light:'night'})).toBe(false);worker.onerror!();expect(c.available()).toBe(false);expect(failed).toBe(1);expect(c.status().pending).toBe(0);c.dispose();});
it('terminates an unresponsive render worker instead of leaving the surface pending indefinitely',()=>{vi.useFakeTimers();try{const failed=vi.fn(),worker={postMessage(){},terminate:vi.fn(),onmessage:null,onerror:null},c=createSceneWorkerClient(()=>worker as unknown as Worker,failed,()=>{});c.submit(view);vi.advanceTimersByTime(16000);expect(failed).toHaveBeenCalledOnce();expect(c.available()).toBe(false);expect(c.status().active).toBe(0);c.dispose();}finally{vi.useRealTimers();}});

it('invalidates fallback maps when loaded chunks change and clears geographic mode explicitly',()=>{const sent:SceneWorkerRequest[]=[],worker={onmessage:null as ((e:{data:SceneWorkerResult})=>void)|null,onerror:null,postMessage(r:SceneWorkerRequest){sent.push(r);},terminate(){}};const c=createSceneWorkerClient(()=>worker as unknown as Worker);c.submit(view);worker.onmessage!({data:result(sent[0])});const local={...view,geography:undefined};c.submit(local);expect(sent[1].scene?.geography).toBeNull();worker.onmessage!({data:result(sent[1])});const loaded={...local,chunks:new Map([['0:0',{status:'ready' as const,level:'detail' as const,base:blank('0:0')} ]])};expect(c.ready(loaded)).toBe(false);c.submit(loaded);expect(sent[2].scene?.chunks).toBe(loaded.chunks);c.dispose();});

it('requests frozen actors after publishing the first static image even while paused',()=>{const sent:SceneWorkerRequest[]=[],worker={onmessage:null as ((e:{data:SceneWorkerResult})=>void)|null,onerror:null,postMessage(r:SceneWorkerRequest){sent.push(r);},terminate(){}};const c=createSceneWorkerClient(()=>worker as unknown as Worker);c.submit(view);worker.onmessage!({data:{...result(sent[0]),staticOnly:true}});expect(c.ready(view)).toBe(true);expect(sent).toHaveLength(2);expect(sent[1].motion).toBe(view.motion);expect(sent[1].scene).toBeUndefined();worker.onmessage!({data:result(sent[1])});expect(sent).toHaveLength(2);c.dispose();});
