import {prepareMobilityFleetAsync,type FleetInput,type FleetRequest,type FleetResult} from '../presentation/mobility-fleet';
import type {MobilityNetwork,MobilityAgent} from '../presentation/mobility-model';
import {buildNetworkJobAsync,type NetworkRequest,type NetworkResult} from '../presentation/mobility-network-job';
import {createVisualTileDecoder,MOBILITY_LAYERS} from './visual-tile-decoder';
export function createMobilityWorkerClient(factory:()=>Worker=()=>new Worker(new URL('./mobility-worker.ts',import.meta.url),{type:'module'})){
 const decoder=createVisualTileDecoder(8*1024*1024,MOBILITY_LAYERS);
 const fallbackBuild=async(request:NetworkRequest)=>{const tiles=[];for(const tile of request.tiles.slice(0,4)){await new Promise<void>(r=>setTimeout(r,0));if(disposed)throw new Error('Mobility worker disposed');tiles.push(decoder.decode(tile));}const result=await buildNetworkJobAsync({...request,tiles},()=>disposed);return {...result,limited:result.limited||tiles.length<request.tiles.length};};
 let worker:Worker|undefined,fallback=false,disposed=false,fleetSequence=0,lastTransitVersion=-1,fleetActive:{request:FleetRequest;network:MobilityNetwork;resolve:(agents:readonly MobilityAgent[])=>void;reject:(error:Error)=>void}|undefined,fleetPending:typeof fleetActive;
 const transitVersions=new WeakMap<object,number>();let transitSequence=0;
 const fallbackFleet=(entry:NonNullable<typeof fleetActive>)=>prepareMobilityFleetAsync(entry.network,entry.request.input,()=>disposed).then(entry.resolve,entry.reject);
 const dispatchFleet=(entry:NonNullable<typeof fleetActive>)=>{fleetActive=entry;if(worker)try{const version=entry.request.input.transitVersion!;worker.postMessage(version===lastTransitVersion?{...entry.request,reuseTransit:true,input:{...entry.request.input,transit:null}}:entry.request);lastTransitVersion=version;}catch{void fallbackFleet(entry).finally(finishFleet);}else void fallbackFleet(entry).finally(finishFleet);};
 const finishFleet=()=>{fleetActive=undefined;if(fleetPending&&!disposed){const next=fleetPending;fleetPending=undefined;dispatchFleet(next);}};
 const pending=new Map<number,{request:NetworkRequest;resolve:(result:NetworkResult)=>void;reject:(error:Error)=>void}>();
 try{worker=factory();worker.onmessage=event=>{if('fleetTicket' in event.data){const result=event.data as FleetResult;if(fleetActive?.request.fleetTicket===result.fleetTicket){fleetActive.resolve(result.agents);finishFleet();}return;}const result=event.data as NetworkResult,entry=pending.get(result.ticket);if(entry){pending.delete(result.ticket);entry.resolve(result);}};worker.onerror=()=>{fallback=true;worker?.terminate();worker=undefined;if(fleetActive)void fallbackFleet(fleetActive).finally(finishFleet);for(const [ticket,entry] of pending){pending.delete(ticket);void fallbackBuild(entry.request).then(entry.resolve,entry.reject);}};}catch{fallback=true;}
 return {fleet(network:MobilityNetwork,input:FleetInput):Promise<readonly MobilityAgent[]>{if(disposed)return Promise.reject(new Error('Mobility worker disposed'));return new Promise((resolve,reject)=>{let transitVersion=0;if(input.transit){transitVersion=transitVersions.get(input.transit)??++transitSequence;transitVersions.set(input.transit,transitVersion);}const entry={network,request:{fleetTicket:++fleetSequence,revision:network.revision,input:{...input,transitVersion}},resolve,reject};if(fleetActive){fleetPending?.resolve([]);fleetPending=entry;}else dispatchFleet(entry);});},build(request:NetworkRequest):Promise<NetworkResult>{if(disposed)return Promise.reject(new Error('Mobility worker disposed'));if(!worker)return fallbackBuild(request);return new Promise((resolve,reject)=>{pending.set(request.ticket,{request,resolve,reject});try{worker!.postMessage(request);}catch{pending.delete(request.ticket);fallback=true;worker?.terminate();worker=undefined;void fallbackBuild(request).then(resolve,reject);}});},status:()=>({fallback,pending:pending.size}),dispose(){disposed=true;worker?.terminate();worker=undefined;for(const entry of pending.values())entry.reject(new Error('Mobility worker disposed'));pending.clear();fleetActive?.reject(new Error('Mobility worker disposed'));fleetPending?.reject(new Error('Mobility worker disposed'));fleetActive=undefined;fleetPending=undefined;decoder.clear();}};
}
